name: Java CI

on: [push]

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up PATH
      run: |
        echo "${ANDROID_HOME}/build-tools/30.0.1" >> $GITHUB_PATH
    - name: Set up JDK 17
      uses: actions/setup-java@v3.6.0
      with:
        distribution: adopt
        java-version: 17
    - name: Build mod jar
      run: chmod +x ./gradlew; ./gradlew deploy -Duse-k2
    - name: Upload built jar file
      uses: actions/upload-artifact@v3
      with:
        name: CHAOS OF CORES
        path: build/libs/${{ github.event.repository.name }}.jar
